-- AlterTable
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "popupHeadline" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "popupBody" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "popupCtaLabel" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "popupCode" TEXT;
