import Link from "next/link";
import type { Metadata } from "next";
import { ArrowUpRight, Check, MessageCircle, FileCheck2, Sparkles } from "lucide-react";
import PartnerForm from "./PartnerForm";
import Earnings from "./Earnings";
export const metadata: Metadata = { title: "Hjälp en restaurang att byta. Få 800 kr. | viaeats", description: "Ett konkret uppdrag i Skåne. Kontakta restaurangägare, visa viaeats och hjälp dem fram till avtal. Vi ger dig material och stöd. Anmäl intresse från 17 år.", alternates: { canonical: "/tipsa" } };
const questions = [
  ["Räcker det att lämna ett restaurangnamn?", "Nej. Du ska kontakta ägaren, presentera erbjudandet och hjälpa dem fram till ett godkänt avtal med viaeats. Ett namn eller ett samtal utan avtal ger ingen ersättning."],
  ["Vad får jag för material?", "Du får exempelsidor, en presentation av plattformen och filmer som visar hur kunden väljer mat, beställer och betalar. Vi går igenom materialet med dig och hjälper dig att svara på ägarens frågor. Du behöver inte göra egna presentationer eller filmer."],
  ["Vem kan anmäla sig?", "Du kan anmäla intresse från 17 år. Vi har ingen övre åldersgräns. Är du under 18 ordnar vi ett särskilt upplägg med vårdnadshavarens godkännande, en vuxen handledare och ett upplägg för utbetalning innan du börjar. Du behöver inte ha eget företag."],
  ["Behöver jag erfarenhet av försäljning?", "Nej. Du behöver kunna ta kontakt med en restaurangägare och förklara erbjudandet tydligt. Vi går igenom upplägget och ger dig godkänt material innan du börjar. Ersättning betalas för resultat, inte för tiden du lägger ner."],
  ["Kan jag tipsa en restaurang som familjen driver?", "Ja, en personlig kontakt går bra. Det måste vara en ny, godkänd restaurangkund med ett riktigt avtal. Berätta om relationen när vi registrerar restaurangen, så undviker vi dubbla anspråk."],
  ["Vilka restauranger passar?", "Både restauranger som redan har en hemsida och vill byta leverantör, och de som behöver sin första beställningssida. Vi börjar i Skåne. Vi godkänner restaurangen och erbjudandet innan du går vidare. viaeats marknadsplats börjar i Lund; vi lovar inte leveranser eller nya kunder i hela Skåne."],
  ["Hur får jag mina pengar?", "Med Swish eller kontoöverföring enligt upplägget vi bestämmer innan du börjar. Swish når normalt fram direkt när vi skickar betalningen. Kontoöverföring tar normalt 1–3 arbetsdagar. Du får 500 kr efter att båda parter har signerat och viaeats godkänt avtalet. Resterande 300 kr betalas senast inom 30 kalenderdagar. Beloppen är före skatt. Om ett egenanställningsföretag betalar din lön gäller deras utbetalningstider; vi förklarar detta före start."],
  ["Är detta ett jobb?", "För vuxna är det ett provisionsbaserat uppdrag. För 17-åringar ordnas ett separat avtal och lönehantering innan start. Vi lovar inget visst antal uppdrag eller framtida jobb. Ett bra samarbete kan öppna för fler möjligheter längre fram."],
];
export default function PartnersPage(){return <>
<section className="partner-hero partner-wrap recruit-hero"><div className="partner-hero-copy"><p className="partner-eyebrow"><span/> ETT UPPDRAG. LOKALA MÖJLIGHETER.</p><h1>Bra på att<br/>ta kontakt?<br/><em>Få 800 kr.</em></h1><p className="partner-small">Per godkänt restaurangavtal. Före skatt.</p><p className="partner-lead">Hjälp restauranger att byta till viaeats beställningssida. <strong>Du tar kontakten. Vi ger dig materialet och sköter tekniken.</strong></p><a className="partner-button" href="#anmalan">Jag vill tjäna extra <ArrowUpRight size={21}/></a><p className="partner-small">Gratis intresseanmälan · Från 17 år · Restauranger i Skåne</p></div><div className="recruit-photo"><img width={1122} height={1402} fetchPriority="high" decoding="async" src="/partners/recruitment/conversation.png" alt="Illustrativ bild av ett samtal med en restaurangägare"/><div className="recruit-photo-label">Människor. Samtal. Nya möjligheter.</div><div className="recruit-reward"><span>PER GODKÄNT RESTAURANGAVTAL</span><strong>800<span> kr</span></strong><p>500 kr efter godkännandet.<br/>300 kr inom 30 dagar.</p><small>Före skatt. <Link href="/tipsa/villkor">Villkor gäller.</Link></small></div></div></section>
<div className="partner-proof-strip"><span><Check size={17}/> Ingen startavgift</span><span><Check size={17}/> Material & introduktion ingår</span><span><Check size={17}/> Stöd hela vägen</span></div>
<section id="sa-funkar-det" className="partner-section partner-wrap"><div className="partner-section-heading"><p className="partner-eyebrow">VAD ÄR UPPGIFTEN?</p><h2>Du öppnar dörren.<br/><span>Vi hjälper dig vidare.</span></h2><p>Du säljer inte mat. Du hjälper restaurangägare att upptäcka ett nytt sätt att ta emot beställningar på sin egen hemsida.</p></div><div className="partner-steps">{[{icon:MessageCircle,n:"01",title:"Ta kontakt.",text:"Efter vår introduktion väljer du en restaurang och stämmer av den med oss. Prata med ägaren om deras beställningssida och kostnad idag."},{icon:Sparkles,n:"02",title:"Visa möjligheten.",text:"Visa våra exempelsidor och filmer. Restaurangen får ett erbjudande att jämföra med sin nuvarande tjänst. Vi hjälper dig med frågorna."},{icon:FileCheck2,n:"03",title:"Hjälp till fram till avtal.",text:"Du håller kontakten fram till signering. När båda parter har signerat och viaeats godkänt avtalet får du ersättning. Vi sköter installationen."}].map(x=><article key={x.n}><div className="partner-step-top"><x.icon size={28}/><span>{x.n}</span></div><h3>{x.title}</h3><p>{x.text}</p></article>)}</div><p className="partner-small">Ett namn eller en intresseanmälan från restaurangen ger ingen ersättning. Det krävs ett godkänt avtal.</p></section>
<section className="partner-earnings-section"><div className="partner-wrap partner-two-col"><div><p className="partner-eyebrow">RÄKNA PÅ DITT MÅL</p><h2>Börja med en.<br/><span>Se vad det kan bli.</span></h2><p>800 kr per godkänt avtal. 500 kr när avtalet är signerat av båda parter och godkänt av viaeats. Resterande 300 kr inom 30 kalenderdagar från godkännandet.</p><p className="partner-small">Resultatbaserad ersättning, ingen fast lön eller garanterad inkomst. Utbetalningsupplägget bestäms innan du börjar. <Link href="/tipsa/villkor">Läs villkoren.</Link></p><a className="partner-button" href="#anmalan">Berätta mer för mig <ArrowUpRight size={20}/></a></div><Earnings/></div></section>
<section id="material" className="partner-section partner-wrap recruit-kit"><div><p className="partner-eyebrow">DU BÖRJAR INTE FRÅN NOLL</p><h2>Du tar samtalet.<br/><span>Vi har materialet.</span></h2><p>Exempelsidor att klicka i, korta filmer och enkla svar på vanliga frågor. Du får en introduktion innan ditt första samtal.</p><div className="recruit-checks"><span><Check/> Mobilvänliga exempelsidor</span><span><Check/> Filmer om beställning & betalning</span><span><Check/> Hjälp med erbjudande & avtal</span></div><Link className="partner-text-link" href="/for-restauranger">Se sidan du kan visa ägaren <ArrowUpRight size={18}/></Link></div><div className="recruit-kit-card"><p className="partner-eyebrow">ETT SÄTT ATT BÖRJA</p><blockquote>”Är du nöjd med er beställningssida och vad den kostar?”</blockquote><p>”Jag samarbetar med viaeats. Vill du se hur det fungerar och jämföra ett erbjudande?”</p><details className="partner-demo-video"><summary>Se din samtalsguide · 60 sekunder <span>▷</span></summary><video controls playsInline preload="none" aria-label="Samtalsguide med musik och text, utan berättarröst" poster="/partners/studio/guide.jpg"><source src="/partners/studio/guide-music.mp4" type="video/mp4"/></video></details></div></section>
<section className="recruit-fit partner-wrap"><div><p className="partner-eyebrow">DIN FÖRSTA KONTAKT KAN FINNAS NÄRA</p><h2>Kvarterets pizzeria.<br/>Ditt favoritställe.<br/><span>En ägare du känner.</span></h2></div><div><p>Du behöver inte ha jobbat med försäljning. Nyfikenhet, tydlighet och viljan att följa upp räcker för att ta första steget.</p><p>Har restaurangen redan en hemsida? Hjälp dem jämföra ett byte. Saknar de en beställningssida? Hjälp dem komma igång.</p><p className="partner-small">Ett bra samarbete kan leda till fler uppdrag eller möjlighet till arbete hos viaeats. Ingen anställning utlovas.</p></div></section>
<section id="anmalan" className="partner-signup-section"><div className="partner-wrap partner-two-col"><div><p className="partner-eyebrow">BÖRJA MED ATT SÄGA HEJ</p><h2>Din nästa möjlighet<br/><span>börjar här.</span></h2><p>Lämna namn och e-post. Vi kontaktar dig, visar materialet och går igenom hur du får betalt. Sedan väljer du om du vill börja.</p><p className="partner-small">Från 17 år, ingen övre åldersgräns. För dig under 18 ordnar vi vårdnadshavarens godkännande, handledning och särskilt avtal innan start. Skolan går först.</p></div><div className="partner-form-card"><h3>Ja, jag är nyfiken.</h3><p>Två uppgifter. Inget åtagande.</p><PartnerForm/></div></div></section>
<section className="partner-section partner-wrap partner-faq"><div><p className="partner-eyebrow">INGA FRÅGETECKEN</p><h2>Bra att veta.</h2></div><div>{questions.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}<Link className="partner-text-link" href="/tipsa/villkor">Alla villkor <ArrowUpRight size={18}/></Link></div></section>
</>}
