import type { Metadata } from "next";
import Link from "next/link";
import { getCompanyInfo } from "@/lib/companyInfo";
export const metadata: Metadata = { title: "Villkor för partnersamarbetet | viaeats", alternates: { canonical: "/tipsa/villkor" } };
export default async function PartnerTerms() {
  const company = await getCompanyInfo();
  return <article className="partner-legal"><p className="partner-eyebrow">Partnerprogram · Version 19 september 2026 · 3</p><h1>Ett tydligt samarbete.<br/>Från första dagen.</h1><p>Det här är villkoren för viaeats program för att hjälpa nya restauranger att ansluta sig. En intresseanmälan är kostnadsfri och innebär inte att du ingår ett uppdragsavtal. Innan du börjar bekräftar vi uppdrag, ersättningsmodell och fakturering skriftligen.</p>
    <h2>1. Vem kan delta?</h2><p>Du kan anmäla intresse från 17 år. Det finns ingen övre åldersgräns. För vuxna genomförs uppdraget genom ett företag med F-skatt eller ett egenanställningsföretag som har godkänt uppdraget och är avtalspart innan arbetet påbörjas.</p><p><strong>För dig som är 17:</strong> intresseanmälan innebär inte att du får börja arbeta. Innan start ska viaeats och du ha ett särskilt skriftligt avtal, dokumenterat godkännande från din vårdnadshavare, en utsedd vuxen handledare, genomförd introduktion och riskbedömning samt överenskomna arbetstider som tar hänsyn till skola och annat arbete. Eget företag krävs inte.</p><p>Ersättningen för 17-åringar hanteras som bruttolön med korrekt löneadministration, skattehantering och eventuella arbetsgivaravgifter. Vem som är arbetsgivare och vilket avtal som gäller ska vara fastställt före start. Om detta inte kan ordnas startar inget arbete. Minderåriga får inte själva underteckna restaurangavtal för viaeats, hantera restaurangens pengar eller göra sena eller oanmälda ensambesök. Kontakter sker på överenskommen dagtid med stöd av handledaren.</p><p>Programmet lovar inget visst antal uppdrag eller någon framtida anställning. För minderåriga reglerar det separata avtalet den faktiska anställnings- och ersättningsformen; rubriken ”samarbete” ersätter inte detta avtal.</p>
    <h2>2. Vad gör du — och vad gör vi?</h2><p>Du presenterar viaeats godkända erbjudande för en restaurangägare och hjälper ägaren fram till signering. Restaurangägaren och viaeats ingår avtalet; du får inte skriva under i viaeats namn eller utlova andra priser, rabatter, leveranser eller ordervolymer. Vi ansvarar för godkännande, teknik, installation och support enligt restaurangens avtal. Erbjudandet gäller både byte från en befintlig leverantör och en första beställningssida. Lägre kostnad ska styrkas genom en jämförelse med restaurangens befintliga avtal. Aktiverade betalsätt, avgifter och eventuell snabbare utbetalning ska bekräftas i restaurangavtalet; inga generella garantier om besparing eller omedelbar utbetalning lämnas.</p><p>Restaurangen kan <Link href="/tipsa/installation">be om en installationstid här</Link>. Förfrågan blir en bokning först när vi har bekräftat tiden.</p>
    <h2>3. Vilka restauranger ger ersättning?</h2><p>Programmet gäller nya restaurangkunder i Skåne. Registrera restaurangen hos din kontakt på viaeats och få skriftligt klartecken innan du arbetar vidare. Befintliga kunder, redan pågående affärer och dubbla tips ger inte flera ersättningar. En restaurang ger en ersättning, även om flera personer hjälper till. Vid flera kontakter gäller den första registrering som viaeats skriftligen har godkänt.</p><p>Familj och bekanta går bra. Berätta om kopplingen och låt ägaren själv ta ställning till ett riktigt restaurangavtal. Förmedlade personuppgifter ska lämnas med kontaktpersonens vetskap. Påhittade kunder, avtal utan ägarens medgivande och vilseledande försäljning godkänns inte.</p>
    <h2>4. Ersättning: 500 kr + 300 kr</h2><ul><li><strong>500 kr direkt efter godkänt avtal:</strong> restaurangens behöriga företrädare och viaeats ska ha signerat. Vi ordnar korrekt utbetalningsunderlag innan avtalet godkänns för ersättning: faktura för fakturerade uppdrag eller löneunderlag för 17-åringens särskilda upplägg. När godkännandet är klart initierar viaeats betalningen av 500 kr. Detta är dag 0.</li><li><strong>300 kr senast inom 30 kalenderdagar från dag 0:</strong> resterande ersättning betalas inom denna tid. Du behöver inte vänta i 30 dagar för att tjäna in den.</li><li><strong>När pengarna når dig:</strong> Direktutbetalning sker med Swish eller kontoöverföring enligt vad vi avtalar före start. Swish når normalt mottagaren direkt när betalningen skickas; kontoöverföring tar normalt 1–3 arbetsdagar. Betalsättet ändrar inte kraven på faktura, löneunderlag eller skattehantering. Vid egenanställning betalar vi avtalsparten, som betalar ut din lön enligt sina tider och villkor; direkt Swish från viaeats till dig utlovas då inte. Vi går igenom detta innan uppdraget börjar.</li></ul><p>För 17-åringar är 800 kr bruttolön före eventuell skatt; arbetsgivaravgifter är arbetsgivarens kostnad och dras inte från den avtalade bruttolönen. För fakturerade uppdrag anges beloppen före skatt, exklusive eventuell moms och före avgifter och löneavdrag hos ett egenanställningsföretag. 800 kr i uppdragsersättning är inte ett löfte om 800 kr utbetalt netto till en privatperson.</p><p><strong>Exempel:</strong> 10 godkända restaurangavtal ger 5 000 kr direkt efter godkännandena och resterande 3 000 kr senast inom 30 dagar från respektive godkännande. Totalt 8 000 kr före skatt och enligt villkoren. Exemplet är ingen prognos eller garanti.</p><p>Ärligt utfört och godkänt arbete påverkas inte av att en restaurang senare väljer att avsluta. Felaktig dubbelutbetalning eller ersättning grundad på oriktiga uppgifter kan behöva rättas; vi kontaktar dig och redovisar skälet.</p>
    <h2>5. Möjlighet att växa med viaeats</h2><p>Ett bra samarbete kan leda till fler uppdrag eller möjlighet till arbete hos viaeats i framtiden. Det är ingen garanti om anställning, arbetstid eller framtida ersättning. Nya uppdrag och en eventuell anställning avtalas separat.</p>
    <h2>6. Avsluta eller ändra samarbetet</h2><p>Du kan sluta ta nya uppdrag när du vill. viaeats kan pausa programmet för nya uppdrag. Redan skriftligen godkända uppdrag följer de villkor som gällde när de godkändes; intjänad ersättning försvinner inte för att programmet ändras. Restaurangens eget avtal reglerar dess pris, uppsägning och eventuella bindningstid.</p>
    <h2 id="integritet">7. Dina uppgifter och kontakt med oss</h2><p>{company.name}{company.organizationNumber ? `, organisationsnummer ${company.organizationNumber},` : ""} ansvarar för personuppgifterna. När du anmäler intresse behandlar vi namn, e-post, tidpunkt för anmälan och eventuell kampanjkälla för att hantera din förfrågan och kontakta dig. Vid installationsförfrågan sparas även restaurangens namn och önskad tid. Vi lägger inte till dig i nyhetsbrev eller kundkampanjer.</p><p>Behandlingen av intresseanmälan bygger på ditt samtycke. Du kan när som helst återkalla det. Uppgifterna i intresselistan används som längst 180 dagar; äldre anmälningar gallras när listan används. Om vi inleder ett samarbete behöver relevanta avtals- och bokföringsuppgifter hanteras separat under den tid som krävs för avtalet och tillämpliga regler.</p><p>Våra leverantörer av drift och lagring kan behandla uppgifterna för vår räkning. Se <Link href="/privacy">viaeats integritetspolicy</Link> för leverantörskategorier, eventuella överföringar och dina rättigheter. Du kan begära tillgång, rättelse eller radering och lämna klagomål till Integritetsskyddsmyndigheten.</p><p>Integritetsfrågor: <a href={`mailto:${company.privacyEmail}`}>{company.privacyEmail}</a>. Frågor om programmet: <a href={`mailto:${company.supportEmail}`}>{company.supportEmail}</a>.</p><Link className="partner-button" href="/tipsa#anmalan">Till intresseanmälan ↗</Link>
  </article>;
}
