import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { createRequire } from 'node:module';
const ts = createRequire(import.meta.url)('typescript');
function fixture(file, previous) {
  const storage=()=>{ const m=new Map(); return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}; };
  let consent=true, now=1789500000000; const events=[]; const listeners=new Map();
  const window={localStorage:previous?.localStorage || storage(),sessionStorage:previous?.sessionStorage || storage(),location:{search:'?utm_source=ig&utm_medium=paid_social&utm_campaign=lund&ad_id=123&fbclid=CLICK',pathname:'/restaurants/palmyra'},parent:null,dispatchEvent:e=>{events.push(e.type);(listeners.get(e.type)||[]).forEach(f=>f());}};window.parent=window;
  const document={referrer:'https://palmyrapizzeria.se/',cookie:'',querySelector:()=>null,createElement:()=>({dataset:{}}),head:{appendChild:()=>{}}};
  const module={exports:{}};
  vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,window,document,localStorage:window.localStorage,URL,URLSearchParams,Date:{now:()=>now},Event:class{constructor(type){this.type=type;}},Set,decodeURIComponent,require:n=>n.includes('cookieConsent')?{hasMarketingConsent:()=>consent}:{journeySessionId:()=> 'session-123'}});
  return {api:module.exports,window,document,events,setConsent:v=>consent=v,advance:ms=>now+=ms};
}
test('annonsen binds genom intern navigation och Stripe-retur',()=>{const f=fixture('../lib/orderAttribution.ts');const first=f.api.orderAttributionContext();assert.equal(first.last.source,'ig');assert.equal(first.last.adId,'123');f.window.location.search='';f.window.location.pathname='/cart';assert.equal(f.api.orderAttributionContext().last.source,'ig');f.document.referrer='https://checkout.stripe.com/';assert.equal(f.api.orderAttributionContext().last.campaign,'lund');});
test('ny kampanj ersätter senaste kontakt men behåller första',()=>{const f=fixture('../lib/orderAttribution.ts');f.api.captureOrderAttribution();f.advance(1000);f.window.location.search='?utm_source=email&utm_campaign=mail';const data=f.api.orderAttributionContext();assert.equal(data.first.source,'ig');assert.equal(data.last.source,'email');});
test('samtyckesnekande ger enbart yta och rensar lagrad marknadsföring',()=>{const f=fixture('../lib/orderAttribution.ts');f.api.captureOrderAttribution();f.setConsent(false);const data=f.api.orderAttributionContext();assert.equal(data.consent,false);assert.equal(data.last,undefined);assert.equal(f.window.localStorage.getItem('viaeats.order-attribution.v1'),null);});
test('kampanjen löper ut och iframe behålls till checkout',()=>{const f=fixture('../lib/orderAttribution.ts');f.window.parent={};assert.equal(f.api.orderAttributionContext().surface,'VIAEATS_EMBED');f.window.parent=f.window;f.window.location.pathname='/cart';f.window.location.search='';f.document.referrer='';f.advance(31*86400000);const data=f.api.orderAttributionContext();assert.equal(data.surface,'VIAEATS_EMBED');assert.equal(data.last.source,'direct');assert.equal(data.last.campaign,undefined);});
test('Metas kö används före laddning och dispatcher efter laddning, init en gång',()=>{const f=fixture('../lib/metaPixelRuntime.ts');f.api.ensureMetaPixel('123');assert.equal(f.window.fbq.queue.length,2);const calls=[];f.window.fbq.callMethod=(...args)=>calls.push(args);f.window.fbq('track','Purchase');assert.equal(calls[0][1],'Purchase');assert.equal(f.window.fbq.queue.length,2);f.api.ensureMetaPixel('123');assert.equal(calls.length,1);});
test('pixeln skapas inte utan samtycke',()=>{const f=fixture('../lib/metaPixelRuntime.ts');f.setConsent(false);f.api.ensureMetaPixel('123');assert.equal(f.window.fbq,undefined);});
test('köp väntar på dispatcher, räknas en gång och samtycke kontrolleras igen',()=>{const f=fixture('../lib/metaEvents.ts');const calls=[];f.window.fbq=(...args)=>calls.push(args);f.api.trackMetaPurchase({orderId:'a',value:123});assert.equal(calls.length,0);f.window.fbq.callMethod=()=>{};f.api.trackMetaPurchase({orderId:'a',value:123});f.api.trackMetaPurchase({orderId:'a',value:123});assert.equal(calls.length,1);assert.equal(calls[0][3].eventID,'Purchase:a');f.setConsent(false);f.api.trackMetaPurchase({orderId:'b',value:123});assert.equal(calls.length,1);});

test('en ny vanlig meny återställer tidigare embed-yta',()=>{const f=fixture('../lib/orderAttribution.ts');f.window.parent={};f.api.captureOrderAttribution();f.window.parent=f.window;f.window.location.search='';f.window.location.pathname='/restaurants/palmyra';f.api.captureOrderAttribution();f.window.location.pathname='/cart';assert.equal(f.api.orderAttributionContext().surface,'VIAEATS_WEB');});
test('mejlreferrer klassas inte som Google-sökning',()=>{const f=fixture('../lib/orderAttribution.ts');f.window.location.search='';f.document.referrer='https://mail.google.com/';assert.equal(f.api.orderAttributionContext().last.source,'email');});

test('direkt återbesök skiljs från tidigare annonskontakt',()=>{const f=fixture('../lib/orderAttribution.ts');f.api.captureOrderAttribution();const g=fixture('../lib/orderAttribution.ts',{localStorage:f.window.localStorage});g.window.location.search='';g.document.referrer='';const data=g.api.orderAttributionContext();assert.equal(data.current.source,'direct');assert.equal(data.last.source,'ig');assert.equal(data.first.source,'ig');});
test('full omladdning från Stripe behåller besökets källa',()=>{const f=fixture('../lib/orderAttribution.ts');f.api.captureOrderAttribution();const g=fixture('../lib/orderAttribution.ts',f.window);g.window.location.search='';g.window.location.pathname='/pay/return';g.document.referrer='https://checkout.stripe.com/';assert.equal(g.api.orderAttributionContext().current.source,'ig');});
test('fördröjt samtycke behåller landningen utan att skriva före samtycke',()=>{const f=fixture('../lib/orderAttribution.ts');f.setConsent(false);f.api.captureOrderAttribution();assert.equal(f.window.localStorage.getItem('viaeats.order-attribution.v1'),null);assert.equal(f.window.sessionStorage.getItem('viaeats.order-attribution.visit.v1'),null);f.window.location.search='';f.window.location.pathname='/cart';f.setConsent(true);const data=f.api.orderAttributionContext();assert.equal(data.current.source,'ig');assert.match(data.fbc,/CLICK$/);});
test('Palmyra och QR-kampanjer har egen källa utan att tappa första kontakt',()=>{const f=fixture('../lib/orderAttribution.ts');f.api.captureOrderAttribution();f.window.location.search='?utm_source=palmyra&utm_medium=qr&utm_campaign=resto';const data=f.api.orderAttributionContext();assert.equal(data.current.source,'palmyra');assert.equal(data.current.medium,'qr');assert.equal(data.first.source,'ig');assert.match(data.fbc,/CLICK$/);});
test('Google braid och TikTok klassas uttryckligen',()=>{const f=fixture('../lib/orderAttribution.ts');f.window.location.search='?wbraid=123';f.document.referrer='';assert.equal(f.api.orderAttributionContext().current.source,'google');f.window.location.search='?utm_source=tiktok&utm_medium=paid_social';assert.equal(f.api.orderAttributionContext().current.source,'tiktok');});
