#!/usr/bin/env bash
#
# sync-local-env.sh — Generate packages/api/.env for LOCAL development by
# pulling the real production secrets from Railway and applying dev-safe
# overrides. Lets the local API behave like prod (Supabase auth, R2 images,
# Google Maps, Adyen TEST, email) while running on http://localhost:4000.
#
#   Run:        bash scripts/sync-local-env.sh
#   Restore:    cp packages/api/.env.bak packages/api/.env   (original minimal env)
#
# What it overrides for local (NEVER copies prod values for these):
#   - NODE_ENV       -> unset (development behaviour: localhost CORS, dev fallbacks)
#   - PORT           -> 4000
#   - DATABASE_URL / DIRECT_URL  -> kept from existing .env.bak (known-good, URL-encoded)
#   - VAPID_*        -> kept from existing .env.bak (not stored on Railway)
#   - Adyen stays in TEST (prod is already TEST, but we assert it)
#
# Multiline push secrets (APNS_KEY_P8, FCM_SERVICE_ACCOUNT_JSON) are skipped —
# they break .env parsing and push is not needed for local login/dpoints work.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API_ENV="$ROOT/packages/api/.env"
BAK="$API_ENV.bak"
RAILWAY_SERVICE="${RAILWAY_SERVICE:-Delivera API}"
RAILWAY_ENV="${RAILWAY_ENV:-production}"

if [ ! -f "$BAK" ]; then
  if [ -f "$API_ENV" ]; then cp "$API_ENV" "$BAK"; echo "Backed up existing .env -> .env.bak"; fi
fi

echo "Pulling prod env from Railway ($RAILWAY_SERVICE / $RAILWAY_ENV)..."
DUMP="$(mktemp)"
trap 'rm -f "$DUMP"' EXIT
railway variables --kv -s "$RAILWAY_SERVICE" -e "$RAILWAY_ENV" > "$DUMP"

# strip one layer of surrounding single/double quotes
unquote() { sed -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'\$/\1/"; }
# val KEY  -> value from the Railway dump (first match, everything after first '=')
val() { grep -m1 "^$1=" "$DUMP" | cut -d= -f2- | unquote || true; }
# bakval KEY -> value preserved from the original local .env.bak
bakval() { [ -f "$BAK" ] && grep -m1 "^$1=" "$BAK" | cut -d= -f2- | unquote || true; }

DATABASE_URL="$(bakval DATABASE_URL)"; DATABASE_URL="${DATABASE_URL:-$(val DATABASE_URL)}"
DIRECT_URL="$(bakval DIRECT_URL)";     DIRECT_URL="${DIRECT_URL:-$(val DIRECT_URL)}"
# Keep payments fully local/test: never pull the prod LIVE Stripe key.
STRIPE_SECRET_KEY="$(bakval STRIPE_SECRET_KEY)"; STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY:-sk_test_dummy_local_dev_only_not_used}"
STRIPE_WEBHOOK_SECRET="$(bakval STRIPE_WEBHOOK_SECRET)"
VAPID_PUBLIC_KEY="$(bakval VAPID_PUBLIC_KEY)"
VAPID_PRIVATE_KEY="$(bakval VAPID_PRIVATE_KEY)"
VAPID_SUBJECT="$(bakval VAPID_SUBJECT)"

cat > "$API_ENV" <<EOF
# ─────────────────────────────────────────────────────────────────────────
# LOCAL DEV ENV — generated by scripts/sync-local-env.sh
# Real prod secrets from Railway (laudable-recreation / $RAILWAY_SERVICE),
# with dev-safe overrides. This file is git-ignored. DO NOT commit.
# Restore original minimal env:  cp packages/api/.env.bak packages/api/.env
# ─────────────────────────────────────────────────────────────────────────

# --- Local overrides (NODE_ENV intentionally unset = development) ---
PORT=4000
LOG_LEVEL=info

# --- Database: SHARED Supabase (same project as prod). NEVER run migrate/db push. ---
DATABASE_URL="$DATABASE_URL"
DIRECT_URL="$DIRECT_URL"

# --- Auth ---
JWT_SECRET=$(val JWT_SECRET)
SUPER_ADMIN_EMAIL=$(val SUPER_ADMIN_EMAIL)
SUPER_ADMIN_PASSWORD=$(val SUPER_ADMIN_PASSWORD)

# --- Supabase (backend service-role + anon) ---
SUPABASE_URL=$(val SUPABASE_URL)
SUPABASE_ANON_KEY=$(val SUPABASE_ANON_KEY)
SUPABASE_SERVICE_ROLE_KEY=$(val SUPABASE_SERVICE_ROLE_KEY)

# --- R2 image storage ---
R2_ACCOUNT_ID=$(val R2_ACCOUNT_ID)
R2_ACCESS_KEY_ID=$(val R2_ACCESS_KEY_ID)
R2_SECRET_ACCESS_KEY=$(val R2_SECRET_ACCESS_KEY)
R2_BUCKET=$(val R2_BUCKET)
R2_JURISDICTION=$(val R2_JURISDICTION)
R2_PUBLIC_BASE_URL=$(val R2_PUBLIC_BASE_URL)

# --- Maps (set both names the API checks) ---
GOOGLE_MAPS_KEY=$(val GOOGLE_MAPS_KEY)
GOOGLE_MAPS_API_KEY=$(val GOOGLE_MAPS_KEY)

# --- Email (real Resend — triggers real emails if you exercise verify/reset) ---
EMAIL_FROM=$(val EMAIL_FROM)
RESEND_API_KEY=$(val RESEND_API_KEY)

# --- Payments (TEST mode — no real charges) ---
PAYMENT_PROVIDER=$(val PAYMENT_PROVIDER)
ADYEN_ENVIRONMENT=TEST
ADYEN_MERCHANT_ACCOUNT=$(val ADYEN_MERCHANT_ACCOUNT)
ADYEN_CLIENT_KEY=$(val ADYEN_CLIENT_KEY)
ADYEN_API_KEY=$(val ADYEN_API_KEY)
ADYEN_HMAC_KEY=$(val ADYEN_HMAC_KEY)
MOLLIE_API_KEY=$(val MOLLIE_API_KEY)
STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET

# --- Web Push (VAPID) — preserved from original local .env (not on Railway) ---
VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY
VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY
VAPID_SUBJECT=$VAPID_SUBJECT

# --- CORS (localhost is auto-allowed in dev; explicit for safety) ---
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:3002
EOF

echo "Wrote $API_ENV"
echo "Sanity (key -> value length, no secrets printed):"
for k in DATABASE_URL JWT_SECRET SUPER_ADMIN_PASSWORD SUPABASE_SERVICE_ROLE_KEY R2_SECRET_ACCESS_KEY GOOGLE_MAPS_KEY VAPID_PRIVATE_KEY; do
  v="$(grep -m1 "^$k=" "$API_ENV" | cut -d= -f2- | tr -d '"')"
  printf '  %-28s %s chars\n' "$k" "${#v}"
done
