"use client";
import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiGet, apiPatch, apiDelete } from "@/shared/api/client";
import { PageHeader, Surface, Button, ErrorPanel } from "@/shared/components/ui";

type Application = { id: string; kind: "partner" | "installation"; name: string; email: string; restaurant?: string; preferredTime?: string; createdAt: string; source: string; campaign?: string; creative?: string; status: "new" | "contacted" };
type Inbox = { items: Application[]; total: number; page: number };
export default function PartnerApplicationsPage() {
  const [page, setPage] = useState(1);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const client = useQueryClient();
  const query = useQuery({ queryKey: ["partner-applications", page], queryFn: () => apiGet<Inbox>(`/partner-applications/admin?page=${page}`), refetchInterval: 60000 });
  const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: "new" | "contacted" }) => apiPatch(`/partner-applications/admin/${id}`, { status }), onSuccess: () => client.invalidateQueries({ queryKey: ["partner-applications"] }) });
  const remove = useMutation({ mutationFn: (id: string) => apiDelete(`/partner-applications/admin/${id}`), onSuccess: async () => { setDeleteId(null); if (query.data?.items.length === 1 && page > 1) setPage(page - 1); await client.invalidateQueries({ queryKey: ["partner-applications"] }); } });
  return <div className="page-stack"><PageHeader title="Partneranmälningar" breadcrumb="Partners" actions={<Button variant="secondary" onClick={() => void query.refetch()}>Uppdatera</Button>}/><Surface className="p-5"><h2 className="section-title">Kontakter att följa upp</h2><p className="section-subtitle">Intresse för samarbete och installation. Bara synligt för superadmin. Listan sparas i upp till 180 dagar.</p><p className="mt-3 text-sm">{query.data?.total ?? "—"} anmälningar · Sida {page}</p></Surface>{query.isLoading && <p role="status">Hämtar anmälningar…</p>}{query.isError && <ErrorPanel title="Kunde inte hämta anmälningarna" action={<Button onClick={() => void query.refetch()}>Försök igen</Button>}/>}{(update.isError || remove.isError) && <p role="alert">Ändringen kunde inte sparas. Försök igen.</p>}{query.data?.items.length === 0 && <Surface className="p-8">Inga anmälningar ännu.</Surface>}<div className="grid gap-4 lg:grid-cols-2">{query.data?.items.map(item => <Surface key={item.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="section-subtitle">{item.kind === "partner" ? "Samarbetspartner" : "Installation"} · {item.status === "new" ? "Ny" : "Kontaktad"}</p><h2 className="section-title">{item.name}</h2><a className="text-sm underline break-all" href={`mailto:${item.email}`}>{item.email}</a></div><span className="text-xs opacity-60">{new Date(item.createdAt).toLocaleDateString("sv-SE")}</span></div>{item.restaurant && <p className="mt-4 text-sm">{item.restaurant}<br/>{item.preferredTime}</p>}<p className="mt-4 text-xs opacity-70">Källa: {item.source} {item.campaign ? `· ${item.campaign}` : ""} {item.creative ? `· ${item.creative}` : ""}</p><div className="mt-5 flex flex-wrap gap-2"><Button variant="secondary" disabled={update.isPending} onClick={() => update.mutate({ id: item.id, status: item.status === "new" ? "contacted" : "new" })}>{item.status === "new" ? "Markera kontaktad" : "Markera som ny"}</Button>{deleteId === item.id ? <><Button disabled={remove.isPending} onClick={() => remove.mutate(item.id)}>Radera permanent</Button><Button variant="secondary" onClick={() => setDeleteId(null)}>Avbryt</Button></> : <Button variant="secondary" onClick={() => setDeleteId(item.id)}>Radera</Button>}</div></Surface>)}</div><div className="flex gap-3"><Button variant="secondary" disabled={page <= 1 || query.isFetching} onClick={() => setPage(page - 1)}>Föregående</Button><Button variant="secondary" disabled={!query.data || page * 50 >= query.data.total || query.isFetching} onClick={() => setPage(page + 1)}>Nästa</Button></div></div>;
}
