"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, ArrowLeft, Check, Plus, ShoppingBag, CreditCard } from "lucide-react";
import { BreathingTrackingPanel } from "@/components/BreathingTracking";
const assets="/partners/studio/";
const themes=[{name:"Palmyra",tag:"PIZZA · LUND",title:"Din favorit.\nDirekt från oss.",dish:"Margherita",image:"pizza.png",color:"pizza",desc:"Tomat, mozzarella och basilika."},{name:"STACK",tag:"BURGERS & GOOD TIMES",title:"Stor smak.\nInget krångel.",dish:"Crispy burger",image:"burger.png",color:"burger",desc:"Krispig kyckling, sallad och dressing."},{name:"GRÖN",tag:"FÄRSKT · FÄRGSTARKT · DITT",title:"Lite grönare.\nMycket godare.",dish:"Dagens sallad",image:"salad.png",color:"green",desc:"Krispiga grönsaker och en god dressing."}];
export default function Studio(){
 const [mode,setMode]=useState<"gallery"|"demo">("gallery"); const [theme,setTheme]=useState(0);const [step,setStep]=useState(0);const [quantity,setQuantity]=useState(1);const [method,setMethod]=useState("Swish");const [status,setStatus]=useState("PREPARING");const [started]=useState(()=>new Date().toISOString());
 const t=themes[theme];
 const [selected,setSelected]=useState<{dish:string;desc:string;image:string;price:number}|null>(null);
 const dish=selected??{...t,price:115};
 useEffect(()=>{window.scrollTo({top:0,behavior:"instant"});},[mode,step,theme]);
 return <div className="vs-studio">
 {mode==="gallery"?<>
 <section className="vs-intro"><p className="vs-kicker">FÖR RESTAURANGER / VIAEATS</p><h1>Er mat. Er hemsida.<br/><em>Enklare att beställa.</em></h1><p>Ge era kunder en modern beställningssida med menyn i fokus och en smidig kassa. Byt från en befintlig tjänst eller börja ta emot beställningar online.</p><button onClick={()=>{setMode("demo");setStep(0)}} className="vs-button">Prova kundupplevelsen <ArrowUpRight size={20}/></button><span className="vs-note">Ingen betalning. Ingen order skickas.</span></section>
 <section id="bestallning" className="vs-films"><div className="vs-section-title"><p className="vs-kicker">01 / FILMER</p><h2>Enkelt för kunden.<br/>Tydligt för er.</h2><p>Riktiga klipp från viaeats, musik och tydlig text som guidar dig genom hela upplevelsen.</p></div><div className="vs-film-grid">{[{slug:"promo",title:"En enklare väg till beställningen.",label:"PROMO · 30 SEK"},{slug:"product",title:"Från hungrig till beställt.",label:"PRODUKTDEMO · 40 SEK"}].map(f=><article key={f.slug}><video controls playsInline preload="none" poster={`${assets}${f.slug}.jpg`} aria-label={f.title}><source src={`${assets}${f.slug}-music.mp4`} type="video/mp4"/></video><p className="vs-kicker">{f.label}</p><h3>{f.title}</h3><div className="vs-film-links"><a href={`${assets}${f.slug}-music.mp4`} download>Ladda ner filmen ↓</a></div></article>)}</div></section>
 <section className="vs-restaurant-benefits"><article><h3>En sida som känns som er.</h3><p>Er meny, era rätter och er identitet. Mobilanpassad från första intrycket till kassan.</p></article><article><h3>Betala på sitt sätt.</h3><p>Swish och kort, med stöd för fler betalsätt som Apple Pay och Klarna. Tillgänglighet beror på aktivering och kundens enhet.</p></article><article><h3>Jämför er månadskostnad.</h3><p>Vi går igenom er nuvarande lösning och lämnar ett tydligt erbjudande. Pris och utbetalningsupplägg bekräftas före avtal.</p></article></section><section className="vs-concepts"><div className="vs-section-title"><p className="vs-kicker">02 / RESTAURANGENS EGEN IDENTITET</p><h2>En tjänst.<br/>Olika personligheter.</h2><p>Tre klickbara designexempel. STACK och GRÖN är fiktiva restauranger. Samtliga beställningar här är demonstrationer.</p></div><div className="vs-concept-grid">{themes.map((c,i)=><button className={`vs-concept ${c.color}`} key={c.name} onClick={()=>{setTheme(i);setSelected(null);setQuantity(1);setStep(0);setMode("demo")}}><span>{c.name}<ArrowUpRight/></span><img loading="lazy" decoding="async" src={assets+c.image} alt={c.dish}/><strong>{c.title}</strong><small>Öppna exempelsidan →</small></button>)}</div></section>
 <section className="vs-terminal-feature"><div><p className="vs-kicker">03 / VID RESTAURANGENS DISK</p><h2>En liten terminal.<br/>En tydlig uppgift.</h2><p>Ta emot beställningen. Se vad som ska lagas. Håll kunden uppdaterad.</p><p className="vs-note">Produktvisualisering baserad på din terminal. Skärmen visar en fiktiv exempelorder.</p></div><div className="vs-terminal-stage"><Terminal/></div></section>
 <section id="kontakt" className="vs-contact"><p className="vs-kicker">NÄSTA STEG FÖR ER RESTAURANG</p><h2>Se vad ett byte<br/>kan göra för er.</h2><p>Berätta vilken restaurang ni driver och vad ni har idag. Vi visar lösningen, jämför kostnaden och går igenom installation och utbetalningar.</p><a className="vs-button" href="/contact">Be om en genomgång ↗</a><p className="vs-note">Har ni redan ett godkänt avtal? <a href="/tipsa/installation">Be om installationstid här.</a></p></section></>:<div className={`vs-demo ${t.color}`}>
 <div className="vs-demo-toolbar"><button onClick={()=>setMode("gallery")}><ArrowLeft size={16}/> Visningsrum</button><span>DEMO · inga riktiga köp</span><button onClick={()=>{setStep(0);setQuantity(1);setStatus("PREPARING")}}>Börja om</button></div>
 <nav className="vs-demo-nav"><strong>{t.name}</strong><span>{t.tag}</span><button aria-label="Visa demovarukorg" onClick={()=>setStep(2)}><ShoppingBag size={20}/></button></nav>
 {step===0?<><section className="vs-restaurant-hero"><div><p className="vs-kicker">GOD MAT. NÄRA DIG.</p><h1>{t.title}</h1><p>Välj din favorit och beställ direkt på vår sida.</p><button className="vs-button" onClick={()=>{setSelected(null);setStep(1)}}>Se menyn <ArrowUpRight size={20}/></button><div className="vs-meta"><span>Avhämtning</span><span>Mobil beställning</span><span>viaeats</span></div></div><img src={assets+t.image} alt={t.dish}/></section><section className="vs-menu"><h2>Något riktigt gott.</h2><div className="vs-menu-grid">{[{...t,price:115},{dish:"King Kong",desc:"Kebabkött, pommes och valfri sås.",image:"wrap.webp",price:135}].slice(0,theme===0?2:1).map(d=><button key={d.dish} onClick={()=>{setSelected(d);setQuantity(1);setStep(1)}}><img src={assets+d.image} alt={d.dish}/><div><h3>{d.dish}</h3><p>{d.desc}</p><strong>{d.price} kr</strong></div><Plus/></button>)}</div><p className="vs-note">Exempelpriser och bildmaterial för demonstration.</p></section></>:null}
 {step===1?<section className="vs-product"><img src={assets+dish.image} alt={dish.dish}/><div><p className="vs-kicker">GÖR DEN TILL DIN</p><h1>{dish.dish}</h1><p>{dish.desc}</p><strong className="vs-price">{dish.price} kr</strong><label className="vs-option"><span>Standard · utan extra tillval</span><Check size={20}/></label><div className="vs-quantity"><button disabled={quantity===1} onClick={()=>setQuantity(n=>Math.max(1,n-1))} aria-label="Minska antal">−</button><strong>{quantity}</strong><button onClick={()=>setQuantity(n=>n+1)} aria-label="Öka antal">+</button></div><button className="vs-button" onClick={()=>setStep(2)}>Lägg i varukorgen · {dish.price*quantity} kr <ShoppingBag size={18}/></button></div></section>:null}
 {step===2?<section className="vs-checkout"><p className="vs-kicker">SNART DAGS ATT ÄTA</p><h1>Din beställning.</h1><div className="vs-checkout-row"><img src={assets+dish.image} alt=""/><div><h3>{quantity} × {dish.dish}</h3><p>Avhämtning · {t.name}</p></div><strong>{quantity*dish.price} kr</strong></div><h3>Hur vill du betala?</h3><div className="vs-methods">{["Swish","Kort och mer"].map(m=><button aria-pressed={method===m} key={m} onClick={()=>setMethod(m)}><CreditCard size={20}/>{m}{method===m&&<Check size={18}/>}</button>)}</div><p className="vs-note">Kort och mer: tillgängliga alternativ beror på enhet och aktivering. Ingen betaltjänst öppnas i demot.</p><div className="vs-total"><span>Totalt</span><strong>{quantity*dish.price} kr</strong></div><button className="vs-button" onClick={()=>setStep(3)}>Simulera slutförd betalning <ArrowUpRight size={18}/></button></section>:null}
 {step===3?<section className="vs-tracking"><p className="vs-kicker">DEMOORDER #1042 · INGEN BETALNING HAR GJORTS</p><BreathingTrackingPanel order={{id:"DEMO-1042",status,restaurantName:t.name,orderType:"PICKUP",selfDelivery:true,createdAt:started,preparingAt:started,estimatedTime:20}} onOpenInfo={()=>setStep(2)}/><div className="vs-status-controls">{[["PREPARING","Tillagas"],["READY","Klar att hämta"],["COMPLETED","Hämtad"]].map(([s,label])=><button key={s} aria-pressed={status===s} onClick={()=>setStatus(s)}>{label}</button>)}</div><p className="vs-note">Samma statuskomponent som används på viaeats. Ordern finns bara i detta demo.</p></section>:null}
 <footer className="vs-demo-footer">Beställningsupplevelse från <b>viaeats</b><span>Designexempel · inte en aktiv restaurangsida</span></footer>
 </div>}
 </div>;
}
function Terminal(){return <div className="vs-terminal"><div className="vs-terminal-lid"><img src="/brand/viaeats-smiley-mark.png" alt=""/><b>viaeats</b></div><div className="vs-printer-slot"/><div className="vs-terminal-screen"><span>PALMYRA PIZZERIA <i>● Öppet</i></span><h3>Ny beställning.</h3><strong>#1042</strong><p>Avhämtning · betald</p><hr/><h4>1 × Margherita</h4><p>Inga extra tillval</p><div>20 min <Check size={16}/></div><small>Exempelorder</small></div><div className="vs-terminal-bottom">‹ <span>○</span> ≡</div></div>}
