import { StyleSheet } from 'react-native';

export const palette = {
  bg: "#171513",
  panel: "#211C19",
  panelMuted: "#2A241F",
  card: "#322A24",
  border: "rgba(255,248,234,0.10)",
  text: "#FFF8EA",
  muted: "#B8AA95",
  gold: "#EAB545",
  goldDark: "#D99500",
  orange: "#F07A13",
  success: "#34C759",
  danger: "#FF6B6B",
  info: "#68B6FF",
};

export const ui = {
  borderRadius: 24,
  buttonHeight: 56,
  padding: 20,
};

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  appBg: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 120,
    gap: 16,
  },
  screen: {
    paddingHorizontal: 20,
    paddingTop: 18,
    gap: 16,
  },
  cartItemList: {
    gap: 14,
  },
  restaurantScreenContent: {
    paddingBottom: 150,
  },
  restaurantHeroWrap: {
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  restaurantHeroCardPremium: {
    minHeight: 360,
    borderRadius: 34,
    overflow: "hidden",
    backgroundColor: palette.panel,
    borderWidth: 1,
    borderColor: "rgba(255,248,234,0.08)",
    justifyContent: "space-between",
  },
  restaurantHeroCoverImage: {
    ...StyleSheet.absoluteFillObject,
    width: undefined,
    height: undefined,
  },
  restaurantHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  restaurantHeroTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  restaurantHeroBackButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(23,21,19,0.78)",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,248,234,0.1)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  restaurantHeroBackText: {
    color: palette.text,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  restaurantHeroActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  restaurantHeroGhostButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(23,21,19,0.78)",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,248,234,0.1)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  restaurantHeroGhostButtonText: {
    color: palette.text,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  restaurantHeroPrimaryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: palette.gold,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  restaurantHeroPrimaryButtonText: {
    color: "#000",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  restaurantHeroContentPremium: {
    paddingHorizontal: 18,
    paddingBottom: 18,
    gap: 12,
  },
  restaurantHeroStatusPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
  },
  restaurantHeroStatusPillOpen: {
    backgroundColor: "rgba(34,197,94,0.12)",
    borderColor: "rgba(34,197,94,0.24)",
  },
  restaurantHeroStatusPillClosed: {
    backgroundColor: "rgba(239,68,68,0.12)",
    borderColor: "rgba(239,68,68,0.22)",
  },
  restaurantHeroStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  restaurantHeroStatusDotOpen: {
    backgroundColor: palette.success,
  },
  restaurantHeroStatusDotClosed: {
    backgroundColor: palette.danger,
  },
  restaurantHeroStatusText: {
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  restaurantHeroStatusTextOpen: {
    color: palette.success,
  },
  restaurantHeroStatusTextClosed: {
    color: palette.danger,
  },
  restaurantHeroTitlePremium: {
    color: palette.text,
    fontSize: 37,
    lineHeight: 40,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: -1.2,
    fontStyle: "italic",
  },
  restaurantHeroTitleAccent: {
    color: palette.gold,
  },
  restaurantHeroMetaRowPremium: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
  },
  restaurantHeroCuisine: {
    color: "rgba(255,248,234,0.52)",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1.4,
  },
  restaurantHeroRatingWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  restaurantHeroRatingText: {
    color: palette.gold,
    fontSize: 12,
    fontWeight: "800",
  },
  restaurantHeroRatingCount: {
    color: "rgba(255,248,234,0.38)",
    fontSize: 11,
    fontWeight: "800",
  },
  restaurantHeroDescriptionPremium: {
    color: "rgba(255,248,234,0.8)",
    fontSize: 14,
    lineHeight: 21,
    maxWidth: "88%",
  },
  restaurantQuickStatsRow: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
    marginTop: 14,
    marginBottom: 20,
  },
  restaurantQuickStatCard: {
    flex: 1,
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 10,
    paddingVertical: 16,
    alignItems: "center",
    gap: 6,
  },
  restaurantQuickStatLabel: {
    color: "rgba(184,170,149,0.76)",
    fontSize: 9,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    textAlign: "center",
  },
  restaurantQuickStatValue: {
    color: palette.text,
    fontSize: 13,
    fontWeight: "900",
    textAlign: "center",
  },
  restaurantStickyNavWrap: {
    paddingHorizontal: 16,
    paddingBottom: 18,
    backgroundColor: palette.bg,
  },
  restaurantStickyNavCard: {
    backgroundColor: "rgba(33,28,25,0.96)",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 10,
    gap: 10,
  },
  restaurantSearchInputWrap: {
    backgroundColor: "rgba(23,21,19,0.88)",
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  restaurantSearchInput: {
    flex: 1,
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
    paddingVertical: 0,
  },
  restaurantCategoryRail: {
    gap: 8,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  restaurantCategoryChip: {
    paddingHorizontal: 18,
    paddingVertical: 13,
    borderRadius: 20,
    backgroundColor: "transparent",
  },
  restaurantCategoryChipActive: {
    backgroundColor: palette.gold,
    shadowColor: palette.gold,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 6,
  },
  restaurantCategoryChipText: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  restaurantCategoryChipTextActive: {
    color: "#000",
  },
  restaurantMenuSectionsWrap: {
    paddingHorizontal: 16,
    gap: 26,
  },
  restaurantMenuSection: {
    gap: 14,
  },
  restaurantMenuSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 4,
  },
  restaurantMenuSectionTitle: {
    color: palette.text,
    fontSize: 28,
    fontWeight: "900",
    textTransform: "uppercase",
    fontStyle: "italic",
    letterSpacing: -0.7,
  },
  restaurantMenuSectionDivider: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255,248,234,0.06)",
  },
  restaurantMenuProductList: {
    gap: 12,
  },
  restaurantMenuProductCard: {
    backgroundColor: palette.panel,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  restaurantMenuProductCardDisabled: {
    opacity: 0.5,
  },
  restaurantMenuProductImage: {
    width: 98,
    height: 98,
    borderRadius: 24,
    backgroundColor: palette.card,
  },
  restaurantMenuProductBody: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 4,
  },
  restaurantMenuProductTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 8,
  },
  restaurantMenuProductTitle: {
    flex: 1,
    color: palette.text,
    fontSize: 16,
    fontWeight: "900",
    textTransform: "uppercase",
    fontStyle: "italic",
    lineHeight: 18,
  },
  restaurantMenuPriceBadge: {
    backgroundColor: "rgba(234,181,69,0.14)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(234,181,69,0.26)",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  restaurantMenuPriceBadgeText: {
    color: palette.gold,
    fontSize: 11,
    fontWeight: "900",
  },
  restaurantMenuProductDescription: {
    color: "rgba(184,170,149,0.82)",
    fontSize: 11,
    lineHeight: 17,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  restaurantMenuProductTags: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 8,
  },
  restaurantMenuDietDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  hero: {
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 16,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 16,
  },
  eyebrow: {
    color: palette.gold,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  heroTitle: {
    color: palette.text,
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "800",
  },
  heroSubtitle: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  logo: {
    width: 64,
    height: 64,
    borderRadius: 18,
  },
  toggleRow: {
    flexDirection: "row",
    gap: 10,
  },
  searchShell: {
    backgroundColor: palette.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchPlaceholder: {
    color: palette.muted,
    fontSize: 14,
  },
  cityPicker: {
    backgroundColor: palette.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  cityText: {
    flex: 1,
    color: palette.text,
    fontSize: 15,
    fontWeight: "600",
  },
  sectionTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 16,
  },
  sectionHeading: {
    color: palette.text,
    fontSize: 20,
    fontWeight: "800",
  },
  chipRow: {
    gap: 10,
    paddingRight: 20,
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: palette.panel,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.border,
  },
  chipActive: {
    backgroundColor: palette.gold,
    borderColor: palette.gold,
  },
  chipText: {
    color: palette.text,
    fontWeight: "700",
  },
  chipTextActive: {
    color: "#000",
  },
  horizontalCards: {
    gap: 12,
    paddingRight: 20,
  },
  dealCard: {
    width: 240,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 22,
    padding: 16,
    gap: 8,
  },
  dealTitle: {
    color: palette.gold,
    fontSize: 16,
    fontWeight: "800",
  },
  dealBody: {
    color: palette.muted,
    lineHeight: 19,
  },
  restaurantCard: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    overflow: "hidden",
    marginBottom: 14,
  },
  restaurantImage: {
    width: "100%",
    height: 170,
  },
  cardTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "800",
    flex: 1,
    paddingRight: 10,
  },
  loaderWrap: {
    paddingVertical: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  floatingCart: {
    position: "absolute",
    bottom: 88,
    right: 20,
    backgroundColor: palette.gold,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  floatingCartText: {
    color: "#000",
    fontWeight: "800",
  },
  bottomTabs: {
    position: "absolute",
    bottom: 20,
    left: 16,
    right: 16,
    backgroundColor: "#110f16",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    paddingVertical: 8,
    flexDirection: "row",
  },
  bottomTab: {
    flex: 1,
    alignItems: "center",
    gap: 5,
  },
  bottomTabLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: palette.panel,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 20,
    maxHeight: "80%",
  },
  modalCardLarge: {
    backgroundColor: palette.panel,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 20,
    maxHeight: "90%",
  },
  productModalBackdrop: {
    justifyContent: "flex-end",
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  productModalScrim: {
    ...StyleSheet.absoluteFillObject,
  },
  productModalSheet: {
    backgroundColor: palette.bg,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderBottomWidth: 0,
    maxHeight: "92%",
    overflow: "hidden",
  },
  productModalHandle: {
    alignSelf: "center",
    width: 54,
    height: 5,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.14)",
    marginTop: 10,
    marginBottom: 4,
  },
  productModalCloseButton: {
    position: "absolute",
    top: 18,
    right: 18,
    zIndex: 5,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(11,10,15,0.82)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  productModalScroll: {
    flexGrow: 0,
  },
  productModalContent: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 28,
    gap: 16,
  },
  productHeroCard: {
    minHeight: 260,
    borderRadius: 28,
    overflow: "hidden",
    backgroundColor: palette.panel,
  },
  productHeroImage: {
    width: "100%",
    height: 260,
  },
  productHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  productHeroContent: {
    position: "absolute",
    left: 18,
    right: 18,
    bottom: 18,
    gap: 10,
  },
  productModalHeader: {
    backgroundColor: palette.panel,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 20,
    gap: 10,
  },
  productHeroPriceChip: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(231,178,75,0.14)",
    borderWidth: 1,
    borderColor: "rgba(231,178,75,0.22)",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  productHeroPriceChipText: {
    color: palette.gold,
    fontSize: 12,
    fontWeight: "800",
  },
  productModalTitle: {
    color: palette.text,
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: -0.6,
  },
  productModalDescription: {
    color: "rgba(249,247,243,0.74)",
    fontSize: 14,
    lineHeight: 21,
  },
  productMetaCard: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  productMetaText: {
    color: palette.muted,
    flex: 1,
    lineHeight: 19,
  },
  productGroupCard: {
    backgroundColor: palette.panel,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    gap: 14,
  },
  productGroupHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  productGroupTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "800",
  },
  productGroupDescription: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  productGroupBadgeRow: {
    alignItems: "flex-end",
    gap: 8,
  },
  productGroupBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
  },
  productGroupBadgeRequired: {
    backgroundColor: "rgba(231,178,75,0.12)",
    borderColor: "rgba(231,178,75,0.22)",
  },
  productGroupBadgeOptional: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderColor: "rgba(255,255,255,0.08)",
  },
  productGroupBadgeText: {
    fontSize: 11,
    fontWeight: "800",
  },
  productGroupBadgeTextRequired: {
    color: palette.gold,
  },
  productGroupBadgeTextOptional: {
    color: palette.muted,
  },
  productGroupCountBadge: {
    backgroundColor: palette.card,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  productGroupCountText: {
    color: palette.text,
    fontSize: 11,
    fontWeight: "700",
  },
  productOptionsList: {
    gap: 10,
  },
  productOptionCard: {
    backgroundColor: palette.card,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  productOptionCardActive: {
    borderColor: "rgba(231,178,75,0.65)",
    backgroundColor: "rgba(231,178,75,0.08)",
  },
  productOptionCardDisabled: {
    opacity: 0.45,
  },
  productOptionMainRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  productOptionIndicator: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.22)",
    alignItems: "center",
    justifyContent: "center",
  },
  productOptionIndicatorActive: {
    borderColor: palette.gold,
    backgroundColor: "rgba(231,178,75,0.12)",
  },
  productOptionIndicatorInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.gold,
  },
  productOptionTextWrap: {
    flex: 1,
    gap: 2,
  },
  productOptionTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "700",
  },
  productOptionTitleActive: {
    color: "#fff5dd",
  },
  productOptionMeta: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  productOptionMetaActive: {
    color: palette.gold,
  },
  productNoteCard: {
    backgroundColor: palette.panel,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    gap: 10,
  },
  productNoteLabel: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  productNoteInput: {
    minHeight: 110,
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: palette.text,
    textAlignVertical: "top",
    lineHeight: 20,
  },
  productSelectionError: {
    backgroundColor: "rgba(244,63,94,0.12)",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(244,63,94,0.2)",
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  productSelectionErrorText: {
    color: "#fecdd3",
    flex: 1,
    lineHeight: 19,
  },
  productModalFooter: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
    backgroundColor: "rgba(18,17,23,0.98)",
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 26,
    gap: 14,
  },
  productFooterSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  productFooterLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  productFooterValue: {
    color: palette.text,
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: -0.4,
    marginTop: 2,
  },
  productQuantityCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: palette.panel,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  productQuantityButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: palette.card,
    alignItems: "center",
    justifyContent: "center",
  },
  productQuantityValue: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "800",
    minWidth: 28,
    textAlign: "center",
  },
  productAddButton: {
    backgroundColor: palette.gold,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  productAddButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  productAddButtonIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(0,0,0,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  productAddButtonLabel: {
    color: "#000",
    fontSize: 16,
    fontWeight: "900",
  },
  productAddButtonSubLabel: {
    color: "rgba(0,0,0,0.58)",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  productAddButtonPrice: {
    color: "#000",
    fontSize: 18,
    fontWeight: "900",
  },
  cityOption: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  header: {
    paddingBottom: 6,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.panel,
    borderWidth: 1,
    borderColor: palette.border,
  },
  headerTitle: {
    color: palette.text,
    fontSize: 28,
    fontWeight: "800",
  },
  headerSubtitle: {
    color: palette.muted,
    fontSize: 14,
    marginTop: 2,
  },
  restaurantHero: {
    padding: 18,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 12,
  },
  restaurantHeroImage: {
    width: "100%",
    height: 180,
    borderRadius: 18,
  },
  restaurantMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  input: {
    backgroundColor: palette.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    color: palette.text,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 12,
  },
  multiline: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  infoCard: {
    width: 220,
    backgroundColor: palette.panelMuted,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 14,
    gap: 8,
  },
  infoCardTitle: {
    color: palette.text,
    fontWeight: "700",
  },
  infoCardBody: {
    color: palette.muted,
    lineHeight: 18,
  },
  sectionBlock: {
    gap: 10,
  },
  productCard: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 14,
    flexDirection: "row",
    gap: 14,
    alignItems: "center",
  },
  productTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  productDescription: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  productPrice: {
    color: palette.gold,
    fontSize: 14,
    fontWeight: "800",
    marginTop: 8,
  },
  productImage: {
    width: 84,
    height: 84,
    borderRadius: 18,
  },
  alertCard: {
    backgroundColor: "#291b14",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#5d4123",
    padding: 18,
    gap: 10,
  },
  alertTitle: {
    color: palette.gold,
    fontSize: 18,
    fontWeight: "800",
  },
  alertText: {
    color: palette.text,
    lineHeight: 19,
  },
  cartItem: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  cartActions: {
    alignItems: "center",
    gap: 12,
  },
  counter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: palette.card,
    minWidth: 92,
  },
  counterText: {
    color: palette.text,
    fontWeight: "800",
  },
  formCard: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 18,
    gap: 10,
  },
  inlineRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  secondaryButton: {
    backgroundColor: palette.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  secondaryButtonLabel: {
    color: palette.text,
    fontWeight: "700",
  },
  helperText: {
    color: palette.muted,
    lineHeight: 18,
  },
  orderCard: {
    backgroundColor: palette.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 14,
  },
  extraRow: {
    backgroundColor: palette.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  extraRowActive: {
    borderColor: palette.gold,
    backgroundColor: "#30220b",
  },
  inlineSummary: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  summaryLabel: {
    color: palette.muted,
    fontSize: 14,
    flex: 1,
  },
  summaryValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  emptyPanel: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButton: {
    backgroundColor: palette.gold,
    borderRadius: 18,
    paddingVertical: 15,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.55,
  },
  primaryButtonLabel: {
    color: "#000",
    fontWeight: "800",
  },
  linkText: {
    color: palette.gold,
    fontWeight: "700",
    textAlign: "center",
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "700",
  },
});
