import { StyleSheet } from 'react-native';
import { lightPalette } from "../theme/palette";

// ── Palette ─────────────────────────────────────────────────────────────────
// The canonical palette lives in src/theme/palette.ts and mirrors the web
// app's CSS tokens (apps/web/app/globals.css). We re-export the LIGHT palette
// here so the `styles` StyleSheet below — which is still imported by ~18
// components and screens — keeps rendering identical light-mode colors as
// before, even though no one imports `palette` from this file anymore.
//
// ── Migration status ────────────────────────────────────────────────────────
// All 33 customer-app components/screens that USED to do
//   `import { palette } from '../constants/theme'`
// have been migrated to subscribe to `useTheme()` from `src/theme`, so they
// pick up dark mode when the OS color scheme flips. See
// `src/theme/ThemeProvider.tsx` for the runtime context.
//
// What's still light-only:
//   - The big `styles` StyleSheet exported at the bottom of this file. It's
//     shared across many components (Header, RestaurantCard, CityModal,
//     ProductModal, etc) and dark-mode-ifying it would require restructuring
//     every consumer to build their own makeStyles factory. The frozen
//     light-mode tokens here are deliberately kept as a safety net.
//   - Anything else that does `import { palette } from '../constants/theme'`
//     in the future — should NOT exist, since the export is now only used
//     internally by `styles` below.
//
// If you need a token that adapts to dark mode, use:
//   const { palette } = useTheme();
// inside your component. Never import `palette` from this file in new code.
export const palette = lightPalette;

// Re-export the new token scales for any local consumers that need them.
export { radii, spacing, fontFamily } from "../theme";

// Keep the `ui` block — `borderRadius` is now aligned with the web's
// `rounded-lg` (14px) instead of the previous chunky 24px.
export const ui = {
  borderRadius: 14,
  buttonHeight: 56,
  padding: 20,
};

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  // Light mode shadow helper – ersätter mörk border
  cardShadow: {
    shadowColor: palette.gold,
    shadowOpacity: 0.08,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  appBg: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 152,
    gap: 16,
  },
  screen: {
    paddingHorizontal: 20,
    paddingTop: 18,
    gap: 16,
  },
  cartItemList: {
    gap: 14,
  },
  restaurantScreenContent: {
    paddingBottom: 150,
  },
  restaurantHeroWrap: {
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  restaurantHeroCardPremium: {
    minHeight: 244,
    borderRadius: 30,
    overflow: "hidden",
    backgroundColor: palette.panel,
    borderWidth: 1,
    borderColor: palette.border,
    justifyContent: "space-between",
    shadowColor: palette.gold,
    shadowOpacity: 0.08,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
  },
  restaurantHeroCoverImage: {
    ...StyleSheet.absoluteFillObject,
    width: undefined,
    height: undefined,
  },
  restaurantHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  restaurantHeroTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingHorizontal: 12,
    paddingTop: 12,
  },
  restaurantHeroBackButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255,249,240,0.94)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(125,97,38,0.14)",
    paddingHorizontal: 11,
    paddingVertical: 8,
    shadowColor: palette.gold,
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  restaurantHeroBackText: {
    color: palette.text,
    fontSize: 10,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.9,
  },
  restaurantHeroActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  restaurantHeroGhostButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255,249,240,0.94)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(125,97,38,0.14)",
    paddingHorizontal: 11,
    paddingVertical: 8,
    shadowColor: palette.gold,
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  restaurantHeroGhostButtonText: {
    color: palette.text,
    fontSize: 10,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  restaurantHeroPrimaryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: palette.gold,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.4)",
    paddingHorizontal: 11,
    paddingVertical: 8,
    shadowColor: palette.gold,
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 4,
  },
  restaurantHeroPrimaryButtonText: {
    color: "#000",
    fontSize: 10,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  restaurantHeroContentPremium: {
    paddingHorizontal: 12,
    paddingBottom: 10,
    gap: 4,
  },
  restaurantHeroStatusPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  restaurantHeroStatusPillOpen: {
    backgroundColor: "rgba(34,197,94,0.12)",
    borderColor: "rgba(34,197,94,0.24)",
  },
  restaurantHeroStatusPillClosed: {
    backgroundColor: "rgba(239,68,68,0.12)",
    borderColor: "rgba(239,68,68,0.22)",
  },
  restaurantHeroStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  restaurantHeroStatusDotOpen: {
    backgroundColor: palette.success,
  },
  restaurantHeroStatusDotClosed: {
    backgroundColor: palette.danger,
  },
  restaurantHeroStatusText: {
    fontSize: 9,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.9,
  },
  restaurantHeroStatusTextOpen: {
    color: palette.success,
  },
  restaurantHeroStatusTextClosed: {
    color: palette.danger,
  },
  restaurantHeroTitlePremium: {
    color: palette.text,
    fontSize: 24,
    lineHeight: 26,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: -0.7,
    fontStyle: "italic",
  },
  restaurantHeroTitleAccent: {
    color: palette.gold,
  },
  restaurantHeroMetaRowPremium: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  restaurantHeroCuisine: {
    color: "rgba(28,28,30,0.52)",
    fontSize: 9,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  restaurantHeroRatingWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  restaurantHeroRatingText: {
    color: palette.goldDark,
    fontSize: 11,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  restaurantHeroRatingCount: {
    color: "rgba(28,28,30,0.38)",
    fontSize: 10,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  restaurantHeroDescriptionPremium: {
    fontFamily: 'Outfit_400Regular',
    color: "rgba(28,28,30,0.8)",
    fontSize: 11,
    lineHeight: 15,
    maxWidth: "88%",
  },
  restaurantQuickStatsRow: {
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 16,
    marginTop: 2,
    marginBottom: 6,
  },
  restaurantQuickStatCard: {
    flex: 1,
    backgroundColor: palette.panel,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 8,
    paddingVertical: 8,
    alignItems: "center",
    gap: 4,
    shadowColor: palette.gold,
    shadowOpacity: 0.05,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  restaurantQuickStatLabel: {
    color: "rgba(125,97,38,0.76)",
    fontSize: 8,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
    textAlign: "center",
  },
  restaurantQuickStatValue: {
    color: palette.text,
    fontSize: 10,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    textAlign: "center",
  },
  restaurantStickyNavWrap: {
    paddingHorizontal: 16,
    paddingBottom: 10,
    backgroundColor: palette.bg,
    zIndex: 10,
    elevation: 10,
  },
  restaurantStickyNavCard: {
    backgroundColor: "rgba(255,248,239,0.98)",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 6,
    gap: 6,
  },
  restaurantSearchInputWrap: {
    backgroundColor: palette.card,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(125,97,38,0.1)",
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  restaurantSearchInput: {
    flex: 1,
    color: palette.text,
    fontSize: 13,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
    paddingVertical: 0,
  },
  restaurantCategoryRail: {
    gap: 6,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  restaurantCategoryChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: "rgba(125,97,38,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  restaurantCategoryChipActive: {
    backgroundColor: palette.gold,
    borderColor: palette.gold,
    shadowColor: palette.gold,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 6,
  },
  restaurantCategoryChipText: {
    color: palette.muted,
    fontSize: 9,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  restaurantCategoryChipTextActive: {
    color: "#000",
  },
  restaurantMenuSectionsWrap: {
    paddingHorizontal: 16,
    gap: 12,
  },
  restaurantMenuSection: {
    gap: 10,
  },
  restaurantMenuSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 4,
  },
  restaurantMenuSectionTitle: {
    color: palette.text,
    fontSize: 22,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    textTransform: "uppercase",
    fontStyle: "italic",
    letterSpacing: -0.7,
  },
  restaurantMenuSectionDivider: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(28,28,30,0.06)",
  },
  restaurantMenuProductList: {
    gap: 10,
  },
  restaurantMenuProductCard: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: palette.gold,
    shadowOpacity: 0.04,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  restaurantMenuProductCardDisabled: {
    opacity: 0.5,
  },
  restaurantMenuProductImage: {
    width: 82,
    height: 82,
    borderRadius: 18,
    backgroundColor: palette.card,
  },
  restaurantMenuProductBody: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 2,
  },
  restaurantMenuProductTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 6,
  },
  restaurantMenuProductTitle: {
    flex: 1,
    color: palette.text,
    fontSize: 15,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    textTransform: "uppercase",
    fontStyle: "italic",
    lineHeight: 17,
  },
  restaurantMenuPriceBadge: {
    backgroundColor: "rgba(217,176,85,0.18)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(125,97,38,0.16)",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  restaurantMenuPriceBadgeText: {
    color: palette.goldDark,
    fontSize: 11,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
  },
  restaurantMenuDiscountedPrice: {
    color: palette.muted,
    fontSize: 10,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    textDecorationLine: "line-through",
  },
  restaurantMenuDiscountedPriceCurrent: {
    color: palette.goldDark,
    fontSize: 11,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
  },
  restaurantMenuProductDescription: {
    color: palette.muted,
    fontSize: 10,
    lineHeight: 15,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  restaurantMenuProductTags: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 8,
  },
  restaurantMenuDietDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  hero: {
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 16,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 16,
  },
  eyebrow: {
    color: palette.goldDark,
    fontSize: 12,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  heroTitle: {
    color: palette.text,
    fontSize: 30,
    lineHeight: 34,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  heroSubtitle: {
    fontFamily: 'Outfit_400Regular',
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  logo: {
    width: 64,
    height: 64,
    borderRadius: 18,
  },
  toggleRow: {
    flexDirection: "row",
    gap: 10,
  },
  searchShell: {
    backgroundColor: palette.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchPlaceholder: {
    fontFamily: 'Outfit_400Regular',
    color: palette.muted,
    fontSize: 14,
  },
  cityPicker: {
    backgroundColor: palette.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  cityText: {
    flex: 1,
    color: palette.text,
    fontSize: 15,
    fontFamily: 'Outfit_600SemiBold',
    fontWeight: "600",
  },
  sectionTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 16,
  },
  sectionHeading: {
    color: palette.text,
    fontSize: 20,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  // Quick-filter chips (sticky ovanför listan)
  quickFilterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: palette.panel,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: "#1C1C1E",
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  quickFilterChipActive: {
    backgroundColor: palette.gold,
    borderColor: palette.gold,
  },
  quickFilterChipText: {
    color: palette.muted,
    fontSize: 11,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
  },
  quickFilterChipTextActive: {
    color: "#000",
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  chipRow: {
    gap: 10,
    paddingRight: 20,
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: palette.panel,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: "#1C1C1E",
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  chipActive: {
    backgroundColor: palette.gold,
    borderColor: palette.gold,
  },
  chipText: {
    color: palette.muted,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
  },
  chipTextActive: {
    color: "#000",
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  horizontalCards: {
    gap: 12,
    paddingRight: 20,
  },
  dealCard: {
    width: 240,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 22,
    padding: 16,
    gap: 8,
  },
  dealTitle: {
    color: palette.goldDark,
    fontSize: 16,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  dealBody: {
    fontFamily: 'Outfit_400Regular',
    color: palette.muted,
    lineHeight: 19,
  },
  restaurantCard: {
    backgroundColor: palette.panel,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    overflow: "hidden",
    marginBottom: 16,
    // "Silk" drop shadow
    shadowColor: "#1C1C1E",
    shadowOpacity: 0.04,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  restaurantImage: {
    width: "100%",
    height: 170,
  },
  cardTitle: {
    color: palette.text,
    fontSize: 18,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
    flex: 1,
    paddingRight: 10,
  },
  loaderWrap: {
    paddingVertical: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  floatingCart: {
    position: "absolute",
    bottom: 88,
    right: 20,
    backgroundColor: palette.gold,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  floatingCartText: {
    color: "#000",
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  bottomTabs: {
    position: "absolute",
    bottom: 20,
    left: 16,
    right: 16,
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    paddingVertical: 8,
    flexDirection: "row",
    shadowColor: "#1C1C1E",
    shadowOpacity: 0.10,
    shadowRadius: 18,
    elevation: 12,
  },
  bottomTab: {
    flex: 1,
    alignItems: "center",
    gap: 5,
  },
  bottomTabLabel: {
    color: palette.muted,
    fontSize: 12,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: palette.panel,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 20,
    maxHeight: "80%",
  },
  modalCardLarge: {
    backgroundColor: palette.panel,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 20,
    maxHeight: "90%",
  },
  productModalBackdrop: {
    justifyContent: "flex-end",
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  productModalScrim: {
    ...StyleSheet.absoluteFillObject,
  },
  productModalSheet: {
    backgroundColor: palette.bg,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderWidth: 1,
    borderColor: palette.border,
    borderBottomWidth: 0,
    maxHeight: "92%",
    overflow: "hidden",
  },
  productModalHandle: {
    alignSelf: "center",
    width: 54,
    height: 5,
    borderRadius: 999,
    backgroundColor: "rgba(125,97,38,0.22)",
    marginTop: 10,
    marginBottom: 4,
    paddingVertical: 12,
    paddingHorizontal: 32,
  },
  productModalCloseButton: {
    position: "absolute",
    top: 18,
    right: 18,
    zIndex: 5,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(28,28,30,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  productModalScroll: {
    flexGrow: 0,
  },
  productModalContent: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 28,
    gap: 16,
  },
  productHeroCard: {
    minHeight: 260,
    borderRadius: 28,
    overflow: "hidden",
    backgroundColor: palette.panel,
  },
  productHeroImage: {
    width: "100%",
    height: 260,
  },
  productHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  productHeroContent: {
    position: "absolute",
    left: 18,
    right: 18,
    bottom: 18,
    gap: 10,
  },
  productHeroTextGradient: {
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 14,
    gap: 8,
  },
  productHeroTitle: {
    color: "#FFF9F2",
    fontSize: 28,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    letterSpacing: -0.6,
    textShadowColor: "rgba(0,0,0,0.28)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  productHeroDescription: {
    color: "rgba(255,249,242,0.92)",
    fontSize: 14,
    lineHeight: 21,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
    textShadowColor: "rgba(0,0,0,0.18)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  productModalHeader: {
    backgroundColor: palette.panel,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 20,
    gap: 10,
  },
  productHeroPriceChip: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(217,176,85,0.18)",
    borderWidth: 1,
    borderColor: "rgba(125,97,38,0.16)",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  productHeroPriceChipText: {
    color: palette.goldDark,
    fontSize: 12,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  productModalTitle: {
    color: palette.text,
    fontSize: 28,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    letterSpacing: -0.6,
  },
  productModalDescription: {
    color: "rgba(33,22,15,0.72)",
    fontSize: 14,
    lineHeight: 22,
    fontFamily: 'Outfit_600SemiBold',
    fontWeight: "600",
  },
  productMetaCard: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  productMetaText: {
    color: palette.muted,
    flex: 1,
    lineHeight: 19,
  },
  productGroupCard: {
    backgroundColor: palette.panel,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    gap: 14,
  },
  productGroupHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  productGroupTitle: {
    color: palette.text,
    fontSize: 18,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  productGroupDescription: {
    fontFamily: 'Outfit_400Regular',
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  productGroupBadgeRow: {
    alignItems: "flex-end",
    gap: 8,
  },
  productGroupBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
  },
  productGroupBadgeRequired: {
    backgroundColor: "rgba(217,176,85,0.16)",
    borderColor: "rgba(125,97,38,0.16)",
  },
  productGroupBadgeOptional: {
    backgroundColor: palette.card,
    borderColor: palette.border,
  },
  productGroupBadgeText: {
    fontSize: 11,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  productGroupBadgeTextRequired: {
    color: palette.goldDark,
  },
  productGroupBadgeTextOptional: {
    color: palette.muted,
  },
  productGroupCountBadge: {
    backgroundColor: palette.panelMuted,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  productGroupCountText: {
    color: palette.text,
    fontSize: 11,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
  },
  productOptionsList: {
    gap: 10,
  },
  productOptionCard: {
    backgroundColor: palette.card,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  productOptionCardActive: {
    borderColor: "rgba(125,97,38,0.24)",
    backgroundColor: "rgba(217,176,85,0.14)",
  },
  productOptionCardDisabled: {
    opacity: 0.45,
  },
  productOptionMainRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  productOptionIndicator: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: "rgba(125,97,38,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  productOptionIndicatorActive: {
    borderColor: palette.gold,
    backgroundColor: "rgba(217,176,85,0.16)",
  },
  productOptionIndicatorInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.gold,
  },
  productOptionTextWrap: {
    flex: 1,
    gap: 2,
  },
  productOptionTitle: {
    color: palette.text,
    fontSize: 15,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
  },
  productOptionTitleActive: {
    color: palette.text,
  },
  productOptionMeta: {
    color: palette.muted,
    fontSize: 12,
    fontFamily: 'Outfit_600SemiBold',
    fontWeight: "600",
  },
  productOptionMetaActive: {
    color: palette.goldDark,
  },
  productNoteCard: {
    backgroundColor: palette.panel,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    gap: 10,
  },
  productNoteLabel: {
    color: palette.text,
    fontSize: 16,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  productNoteInput: {
    fontFamily: 'Outfit_400Regular',
    minHeight: 110,
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: palette.text,
    textAlignVertical: "top",
    lineHeight: 20,
  },
  productSelectionError: {
    backgroundColor: "rgba(244,63,94,0.12)",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(244,63,94,0.2)",
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  productSelectionErrorText: {
    fontFamily: 'Outfit_400Regular',
    color: "#9F1239",
    flex: 1,
    lineHeight: 19,
  },
  productModalFooter: {
    borderTopWidth: 1,
    borderTopColor: palette.border,
    backgroundColor: "rgba(255,248,239,0.98)",
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 26,
    gap: 14,
  },
  productFooterSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  productFooterLabel: {
    color: palette.muted,
    fontSize: 12,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
  },
  productFooterValue: {
    color: palette.text,
    fontSize: 24,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    letterSpacing: -0.4,
    marginTop: 2,
  },
  productQuantityCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: palette.panel,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  productQuantityButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: palette.card,
    alignItems: "center",
    justifyContent: "center",
  },
  productQuantityValue: {
    color: palette.text,
    fontSize: 18,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
    minWidth: 28,
    textAlign: "center",
  },
  productAddButton: {
    backgroundColor: palette.gold,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  productAddButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  productAddButtonIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(0,0,0,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  productAddButtonLabel: {
    color: "#000",
    fontSize: 16,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
  },
  productAddButtonSubLabel: {
    color: "rgba(0,0,0,0.58)",
    fontSize: 12,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
    marginTop: 2,
  },
  productAddButtonPrice: {
    color: "#000",
    fontSize: 18,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
  },
  cityOption: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  header: {
    paddingBottom: 6,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.panel,
    borderWidth: 1,
    borderColor: palette.border,
  },
  headerTitle: {
    color: palette.text,
    fontSize: 28,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  headerSubtitle: {
    fontFamily: 'Outfit_400Regular',
    color: palette.muted,
    fontSize: 14,
    marginTop: 2,
  },
  restaurantHero: {
    padding: 18,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 12,
  },
  restaurantHeroImage: {
    width: "100%",
    height: 180,
    borderRadius: 18,
  },
  restaurantMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  input: {
    fontFamily: 'Outfit_400Regular',
    backgroundColor: palette.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    color: palette.text,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 12,
  },
  multiline: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  infoCard: {
    width: 220,
    backgroundColor: palette.panelMuted,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 14,
    gap: 8,
  },
  infoCardTitle: {
    color: palette.text,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
  },
  infoCardBody: {
    fontFamily: 'Outfit_400Regular',
    color: palette.muted,
    lineHeight: 18,
  },
  sectionBlock: {
    gap: 10,
  },
  productCard: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 14,
    flexDirection: "row",
    gap: 14,
    alignItems: "center",
  },
  productTitle: {
    color: palette.text,
    fontSize: 16,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  productDescription: {
    fontFamily: 'Outfit_400Regular',
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  productPrice: {
    color: palette.goldDark,
    fontSize: 14,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
    marginTop: 8,
  },
  productImage: {
    width: 84,
    height: 84,
    borderRadius: 18,
  },
  alertCard: {
    backgroundColor: "rgba(217,176,85,0.14)",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(125,97,38,0.16)",
    padding: 18,
    gap: 10,
  },
  alertTitle: {
    color: palette.goldDark,
    fontSize: 18,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  alertText: {
    fontFamily: 'Outfit_400Regular',
    color: palette.text,
    lineHeight: 19,
  },
  cartItem: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  cartActions: {
    alignItems: "center",
    gap: 12,
  },
  counter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: palette.card,
    minWidth: 92,
  },
  counterText: {
    color: palette.text,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  formCard: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 18,
    gap: 10,
  },
  inlineRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  secondaryButton: {
    backgroundColor: palette.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  secondaryButtonLabel: {
    color: palette.text,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
  },
  helperText: {
    fontFamily: 'Outfit_400Regular',
    color: palette.muted,
    lineHeight: 18,
  },
  orderCard: {
    backgroundColor: palette.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 14,
  },
  extraRow: {
    backgroundColor: palette.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  extraRowActive: {
    borderColor: palette.gold,
    backgroundColor: "rgba(217,176,85,0.14)",
  },
  inlineSummary: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  summaryLabel: {
    fontFamily: 'Outfit_400Regular',
    color: palette.muted,
    fontSize: 14,
    flex: 1,
  },
  summaryValue: {
    color: palette.text,
    fontSize: 14,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
  },
  emptyPanel: {
    backgroundColor: palette.panel,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButton: {
    backgroundColor: palette.gold,
    borderRadius: 18,
    paddingVertical: 15,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.55,
  },
  primaryButtonLabel: {
    color: "#000",
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
  },
  linkText: {
    color: palette.goldDark,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
    textAlign: "center",
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  badgeText: {
    fontSize: 12,
    fontFamily: 'Outfit_700Bold',
    fontWeight: "700",
  },
  discountedRail: {
    paddingTop: 10,
    paddingBottom: 6,
    backgroundColor: palette.bg,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(125,97,38,0.08)",
  },
  discountedRailHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  discountedRailHeaderText: {
    color: palette.gold,
    fontSize: 9,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
    letterSpacing: 1.5,
  },
  discountedRailHeaderLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(125,97,38,0.12)",
  },
  discountedRailContent: {
    gap: 8,
    paddingHorizontal: 16,
    paddingRight: 20,
  },
  discountedProductCard: {
    width: 92,
    borderRadius: 12,
    backgroundColor: palette.panel,
    borderWidth: 1,
    borderColor: "rgba(125,97,38,0.13)",
    overflow: "visible",
    shadowColor: palette.gold,
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  discountedProductImage: {
    width: "100%",
    height: 52,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    overflow: "hidden",
  },
  discountedBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: palette.gold,
    borderRadius: 6,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  discountedBadgeText: {
    color: "#fff",
    fontSize: 8,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
  },
  discountedProductInfo: {
    padding: 5,
  },
  discountedProductTitle: {
    color: palette.text,
    fontSize: 9,
    fontFamily: 'Outfit_800ExtraBold',
    fontWeight: "800",
    marginBottom: 2,
  },
  discountedPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  discountedOriginalPrice: {
    fontFamily: 'Outfit_400Regular',
    color: palette.muted,
    fontSize: 8,
    textDecorationLine: "line-through",
  },
  discountedNewPrice: {
    color: palette.goldDark,
    fontSize: 10,
    fontFamily: 'Outfit_900Black',
    fontWeight: "900",
  },
});
